name: main

on:
  push:
    branches: [ '*' ]
  pull_request:
  release:
    types: [ created, edited ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build frontend
        run: make build-frontend
      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
      - name: Sed Config
        shell: bash
        run: |
          timestamp=`TZ="Asia/Shanghai" date +"%Y%m%d%H%M%S"`
          TAGS_OPT="sc$timestamp"
          echo "TAGS_OPT=$TAGS_OPT" >> $GITHUB_ENV  # 将 TAGS_OPT 变量导出为环境变量
          docker build -t registry.cn-hangzhou.aliyuncs.com/startzyp/vcloud-filebrowser:$TAGS_OPT .
      - name: push docker
        shell: bash
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/startzyp/vcloud-filebrowser:$TAGS_OPT
      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}

